config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="row">
      <div class= "col-3">
       <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
          <br />
          You know
          <br />
          you need
          <br />
          to code
         </div>
       <% end %>  
      </div>
      <div class="col-4 slogan">
        Splurting out unsolicited advice about entrepreneurship since 2016
       </div>
       <div class="col-5 links">
        <%= link_to 'Contribute', new_quote_path %>
        <%= link_to 'About', '#' %>
      </div>   
    </header>

    <hr />

    <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
         </div>
         <div class="col-6 footer-blurb">
          Proudly hacked by <a href="[YOUR_PORTFOLIO_URL]">Allina</a><br />
          Want to build your own Splurty Web App - <a href="https://online.bootcampspot.com">Learn how to code here</a>
      </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/quotes/index.html.erb
<h1><%= @quote.saying %></h1>
<h2>- <%= @quote.author %></h2>

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>